[package]
name = "ray_trace_rs"
version = "0.1.0"
authors = ["Matthew Burket <m@tthewburket.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
overload = "0.1.1"
